version: 2
jobs:
  build:
    docker:
      - image: cimg/php:8.2.6
    steps:
      - checkout
      - run: 
          name: Build Dependencies
          command: make build
      - run:
          name: Validate PHP-CS-FIXER
          command: make validate-cs 
      - run:
          name: PHPUnit Tests (Unit / Functional)
          command: make test 
      - store_test_results:
          path: build/logs
